### ISSUE TITLE
Missing getters in org.audit4j.handler.db.DatabaseAuditHandler

### ISSUE THREAD

**Issue by ltlBeBoy** [audit4j/audit4j-db#8]
**Audit4J version: 2.4.1**
**Audit4J-db version: 2.4.1**
**yamlbeans version: 1.09**
**Configuration (YAML):**

```
!Configuration

layout: !org.audit4j.core.layout.SimpleLayout {}

handlers:
- !org.audit4j.handler.db.DatabaseAuditHandler
  embedded: false
  db_connection_type: pooled
  db_driver: com.mysql.jdbc.Driver
  db_url: jdbc:mysql://localhost/audit4j
  db_user: db_user
  db_password: db_password
  db_datasourceClass: com.mysql.jdbc.jdbc2.optional.MysqlDataSource

metaData: !org.audit4j.core.DummyMetaData {}
```

**Problem:**
The initialization fails when using pooled database connection type because the property _db_datasourceClass_ was not found in class _org.audit4j.handler.db.DatabaseAuditHandler_:

```
Audit4j:INFO Initializing Audit4j...
Audit4j:INFO Loading Configurations...
Audit4j:WARN Audit4j Terminated due to critical error.
Audit4j:ERROR Failed to initialize Audit4j: initialization failed.!!
org.audit4j.core.exception.ConfigurationException: Configuration Exception
	at org.audit4j.core.YAMLConfigProvider.readConfig(YAMLConfigProvider.java:90)
	at org.audit4j.core.Configurations.loadConfig(Configurations.java:83)
	at org.audit4j.core.Configurations.loadConfig(Configurations.java:71)
	at org.audit4j.core.Context.loadConfig(Context.java:327)
	at org.audit4j.core.Context.init(Context.java:126)
	at org.audit4j.core.Context.initWithConfiguration(Context.java:233)
	at de.mkmultimedia.audit.Audit4JTest.main(Audit4JTest.java:17)
Caused by: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 14, column 21: Unable to find property 'db_datasourceClass' on class: org.audit4j.handler.db.DatabaseAuditHandler
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:292)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:152)
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:335)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:152)
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:295)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:152)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:103)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:90)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:84)
	at org.audit4j.core.YAMLConfigProvider.readConfig(YAMLConfigProvider.java:88)
	... 6 more
```

This error occures because the YAML reader calls the utility class [Beans which checks for the getter of the property first](https://github.com/EsotericSoftware/yamlbeans/blob/yamlbeans-1.09/src/com/esotericsoftware/yamlbeans/Beans.java#L147) before calling the setter.

**Solution:**
Add getters for the following properties to the class _org.audit4j.handler.db.DatabaseAuditHandler_:
- separate
- dataSource
- table_prefix
- table_suffix
- default_table_name
- db_pool_autoCommit
- db_pool_connectionTimeout
- db_pool_idleTimeout
- db_pool_maxLifetime
- db_pool_minimumIdle
- db_pool_maximumPoolSize
- db_datasourceClass

**Comment by janithb** [comment]
This is fixed from #12
